version: "3"

services:
  db:
    image: mysql:8.2
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  app:
    build:
      context: node
      dockerfile: Dockerfile.prod
    image: wesleypradodev/app:prod
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    container_name: app
    entrypoint: [
        "/bin/sh",
        "-c",
        "dockerize -wait tcp://db:3306 -timeout 20s && docker-entrypoint.sh && node app.js"]
    depends_on:
      - db
    networks:
      - node-network
    
  nginx:
    build: 
      context: nginx
      dockerfile: Dockerfile.prod
    image: wesleypradodev/nginx:prod
    container_name: nginx
    networks: 
      - node-network
    ports: 
      - "8080:80"
    depends_on:
      - app

networks:
  node-network:
    driver: bridge

volumes:
  db_data: